### ISSUE TITLE
Replace Local SQLite with Render.com SQL for Persistent Storage

### ISSUE THREAD

**Issue by thefcraft** [Suryanshj45/MnC-TPC#2]
It has been observed that the current implementation uses a local SQLite database (collage_company.db) for storage. This leads to data loss when the server goes inactive, as the storage is not persistent.

Proposed Solution: Switch to a free SQL cloud storage solution, such as Render.com SQL, to ensure that the data remains persistent even when the server is inactive.

Steps to Reproduce:

1. Run the application using the current local SQLite database.
2. Let the server go inactive.
3. Restart the server and check for data integrity.

Expected Outcome: Data should remain intact and accessible after the server is restarted.

Actual Outcome: Data is lost after the server goes inactive.

**Comment by Suryanshj45** [comment]
Raise Merge Request
